"""add language to posts

Revision ID: 077a27952858
Revises: 947c1476bfc1
Create Date: 2019-10-08 16:17:15.014415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077a27952858'
down_revision = '947c1476bfc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
