"""empty message

Revision ID: 485574d1c9bf
Revises: c68c03b362c7
Create Date: 2021-05-22 10:29:52.916043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485574d1c9bf'
down_revision = 'c68c03b362c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
