"""post language added

Revision ID: 873ee2f2c5e8
Revises: 485574d1c9bf
Create Date: 2021-05-28 13:10:45.996833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873ee2f2c5e8'
down_revision = '485574d1c9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
